### PR TITLE
Fix want to attend text color

### PR DESCRIPTION
**Pull request by Dheerajjha451**
Phone
other

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
Please remove the package-lock.json, and there is a much simpler way to do the styling (text-white md:text-black will do the same thing.)

**Comment by Dheerajjha451** [comment]
@ChristianBingman Is it okay now?

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
The styling is better, but you completely deleted the package-lock.json 🤣. It is really annoying sometimes. You can fix it by running `git checkout main -- package-lock.json` and committing the changes 👍🏼.

**Comment by Dheerajjha451** [comment]
@ChristianBingman  Sorry for the inconvenience; I am new to github and did my best to complete the desired task correctly. I hope that this time it will be correct.

**Review by ChristianBingman — APPROVED** [review]
LGTM 👍

**Pull request merged**
