### PR TITLE
fixed speaker section to center for medium screens

### PR DESCRIPTION
**Pull request by Abhishek7Tech**

### CODE REVIEW

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
I can tell from the code that this implementation will be very buggy. Some things like huge padding numbers, switching between flex-col and flex-row unnecessarily. Check out the Sponsors section for a good example of what needs to be done here.

**Comment by Abhishek7Tech** [comment]
@ChristianBingman flex-col is for small screens as all the images will be in a vertical line.
                                 flex-row is for medium and large screens as all images needs to be in a horizontal line.
                                 I have removed the margins and paddings as well.

**Comment by Abhishek7Tech** [comment]
This is how it looks like now.
https://user-images.githubusercontent.com/93655183/222877498-43d03424-e64a-45b1-95be-1e8e8aa3d5e4.mp4

**Review by ChristianBingman — CHANGES_REQUESTED** [review]
Please checkout package-lock from main. `git checkout main -- package-lock.json`

**Comment by ChristianBingman** [comment]
It looks like a lot of other files were committed, might be worth just starting over.

**Pull request closed without merging**
